name: Build PS4 Payload

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake binutils gcc-multilib g++-multilib

      - name: Setup OpenOrbis SDK
        run: |
          git clone https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain.git $HOME/sdk
          echo "OO_PS4_TOOLCHAIN=$HOME/sdk" >> $GITHUB_ENV
          echo "$HOME/sdk/bin" >> $GITHUB_PATH

      - name: Build Payload
        run: |
          mkdir -p build
          make OO_PS4_TOOLCHAIN=$HOME/sdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS4-Payload
          path: Payload.bin


