name: Build PS4 Payload

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake binutils gcc-multilib g++-multilib wget unzip

      - name: Setup OpenOrbis SDK
        run: |
          # تحميل الإصدار 0.5.3
          wget https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.3/OpenOrbis-PS4-Toolchain-0.5.3.zip -O sdk.zip
          unzip sdk.zip
          
          # إنشاء مجلد الـ sdk ونقل الملفات من المجلد المستخرج
          mkdir -p $HOME/sdk
          mv OpenOrbis-PS4-Toolchain-0.5.3/* $HOME/sdk/
          
          # تفعيل متغيرات البيئة
          echo "OO_PS4_TOOLCHAIN=$HOME/sdk" >> $GITHUB_ENV
          echo "$HOME/sdk/bin" >> $GITHUB_PATH

      - name: Build Payload
        run: |
          mkdir -p build
          make OO_PS4_TOOLCHAIN=$HOME/sdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS4-Payload
          path: Payload.bin
