name: Build PS4 Payload

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake binutils gcc-multilib g++-multilib wget

      - name: Setup OpenOrbis SDK
        run: |
          wget https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/archive/refs/tags/v0.5.3.tar.gz -O sdk.tar.gz
          mkdir -p $HOME/sdk
          tar -xzf sdk.tar.gz -C $HOME/sdk --strip-components=1
          
          mkdir -p $HOME/sdk/lib
          wget https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.2/libSceKernel.a -O $HOME/sdk/lib/libSceKernel.a
          wget https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.2/libSceSysUtil.a -O $HOME/sdk/lib/libSceSysUtil.a

          echo "OO_PS4_TOOLCHAIN=$HOME/sdk" >> $GITHUB_ENV
          echo "$HOME/sdk/bin" >> $GITHUB_PATH

      - name: Build Payload
        run: |
          mkdir -p build
          make OO_PS4_TOOLCHAIN=$HOME/sdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS4-Payload
          path: Payload.bin
